language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

addons:
  homebrew:
    update: true
    brewfile: true

  apt:
    packages:
      - autoconf

env:
  - CONF: default
  - CONF: goffice

script:
    - echo "export CC=$CC" > travis-ci/env
    - echo "export TRAVIS_OS_NAME=$TRAVIS_OS_NAME" >> travis-ci/env
    - echo "export CONF=$CONF" >> travis-ci/env

    # Command to execute
    - CMD=". travis-ci/env ; travis-ci/check && make && ./pouet"

    - sh -c "$CMD"
