sudo: required

language: c

services:
  - docker

env:
  - DIST_NAME: debian
    DIST_VERS: testing
    TAG: grisbi

before_install:
    - docker pull ${DIST_NAME}:${DIST_VERS}
    - docker build --rm=true --file=Dockerfile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:${TAG} .

script:
    - docker run --volume=`pwd`:/build ${DIST_NAME}-${DIST_VERS}:${TAG}
      sh -c "
      make && ./pouet
      "
