sudo: required

language: c

services:
  - docker

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - DIST_NAME: debian
    DIST_VERS: testing
    TAG: grisbi

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ${DIST_NAME}:${DIST_VERS} ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --rm=true --file=travis-ci/Dockerfile.${DIST_NAME}-${DIST_VERS} --tag=${DIST_NAME}-${DIST_VERS}:${TAG} travis-ci ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtk+3 ; fi

script:
    - echo "export CC=$CC" > travis-ci/env
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --volume=`pwd`:/build ${DIST_NAME}-${DIST_VERS}:${TAG}
      sh -c "
      . travis-ci/env ;
      travis-ci/check && make && ./pouet
      " ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sh -c "
      travis-ci/check ; make && ./pouet
      " ; fi
