#!/bin/sh

set -e
set -x

echo "CC: $CC"
$CC --version

echo "TRAVIS_OS_NAME:" $TRAVIS_OS_NAME
case "$TRAVIS_OS_NAME" in 
	*linux*)
		echo "Linux"
		;;
	*osx*)
		echo "macOS"
		;;
esac

autoconf --version
