FROM debian:testing
MAINTAINER Ludovic Rousseau

RUN apt-get -y update \
	&& apt-get install -y \
		build-essential \
		autoconf \
		clang \
		libssl-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir /build
WORKDIR /build
